language: cpp
install:
  - sudo apt-get -qq update
  - sudo apt-get install -y cmake libcppunit-dev
before_script:
  - cmake .
  - make
script: 
    - ./runtest.sh
sudo: required
dist: trusty
notifications:
  slack: 'dashee:LfPfKQOhQ0NK2vUmSJ8iuruX'